# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home    # Redirect to home after login
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
                enable_csrf: true
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                target: home    # Redirect to home after logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/instructeur, roles: ROLE_INSTRUCTEUR }
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }