version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/src   # Monte seulement le répertoire src
      - ./vendor:/var/www/html/vendor # Monte le répertoire vendor si nécessaire
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env # Monte le fichier .env dans le conteneur
      - ./config:/var/www/html/config # Monte le répertoire config
      - ./templates:/var/www/html/templates
      - ./public:/var/www/html/public
    networks:
      - symfony-network
    command:
      sh -c "composer --version && php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - symfony-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: b2academy
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_Utilisateur : root
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - symfony-network

volumes:
  mysql_data:

networks:
  symfony-network:
